name: Karusc CD

on: 
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: KaruscWebAppDev    
  AZURE_WEBAPP_PACKAGE_PATH: '.'    
  DOTNET_VERSION: '8.0.100'
  DOTNET_EF_VERSION: '8.0.0'

jobs:
  karusc-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}  
      
    - name: Publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/karusc 

    - name: Update database
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        dotnet tool install -g dotnet-ef --version ${{ env.DOTNET_EF_VERSION }}
        export KARUSC_DB_CONNECTION_STRING="${{ secrets.DATABASE_CONNECTION_STRING }}"
        dotnet ef database update -p Karusc.Server.Infrastructure -s Karusc.Server
          
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/karusc'