name: Deploy main

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: configure git
        run: |
          git config user.name "abhinavsrivas7"
          git config user.email "130465627+abhinavsrivas@users.noreply.github.com"

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: add origin
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: deploy
        run: npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}